/* eslint-disable */
// AUTO-GENERATED by scripts/gen-types.ts from schemas/*.schema.json — DO NOT EDIT.

/**
 * Measured facts about every source (engine-computed) plus optional semantic labels (added by Claude from contact sheets or by vision models). Never contains decisions.
 */
export interface Analysis {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  generatedAt: string;
  /**
   * Tool name → version, for reproducibility.
   */
  tools?: {
    [k: string]: string;
  };
  sources: SourceAnalysis[];
}
export interface SourceAnalysis {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  sourceId: string;
  shots: Shot[];
  blackSegments?: {
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    start: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    end: number;
  }[];
  frozenSegments?: {
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    start: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    end: number;
  }[];
  audio: AudioAnalysis;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  transcriptRef?: string;
  contactSheets?: string[];
}
export interface Shot {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  /**
   * Time in seconds. Snapped to the nearest frame at render time.
   */
  start: number;
  /**
   * Time in seconds. Snapped to the nearest frame at render time.
   */
  end: number;
  /**
   * Strength of the cut that opens this shot.
   */
  sceneScore?: number;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  keyframe?: string;
  luma?: {
    mean?: number;
    p05?: number;
    p95?: number;
    /**
     * 98th percentile (code value / 255, like the others). Note: p05/p95 are signalstats' 10th/90th percentiles.
     */
    p98?: number;
  };
  exposure?: "under" | "ok" | "over" | "mixed";
  saturationMean?: number;
  /**
   * Used for white-balance estimation and camera matching.
   *
   * @minItems 3
   * @maxItems 3
   */
  rgbMean?: [number, number, number];
  /**
   * @maxItems 6
   */
  dominantColors?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string];
  motionScore?: number;
  sharpness?: number;
  faces?: {
    maxCount?: number;
    /**
     * Per-frame boxes stored out-of-line (can be large).
     */
    track?: string;
  };
  labels?: {
    /**
     * e.g. 'person', 'product', 'talking-head', 'wide', 'close-up', 'logo'
     */
    label: string;
    confidence?: number;
    source: "claude" | "model" | "user";
  }[];
  /**
   * Free semantic description (Claude annotation).
   */
  notes?: string;
  qualityScore?: number;
}
export interface AudioAnalysis {
  integratedLufs?: number;
  loudnessRange?: number;
  truePeakDb?: number;
  noiseFloorDb?: number;
  clipping?: boolean;
  humHz?: 50 | 60 | null;
  silences?: {
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    start: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    end: number;
  }[];
  speech?: {
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    start: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    end: number;
  }[];
  /**
   * Music in ≥ 20 % of the non-silent duration (from content). A music bed is never denoised as noise.
   */
  musicDetected?: boolean;
  content?: AudioContent;
  noiseProfile?: ("broadband" | "hum" | "hiss" | "wind" | "traffic" | "hvac" | "reverb" | "crowd")[];
  qualityScore?: number;
}
/**
 * What the audio contains, per segment: speech, music, ambient noise or silence ("speech+music" = a voice over a music bed). Measured accuracy and limits: docs/measurements/audio-content.md.
 */
export interface AudioContent {
  /**
   * spectral-only: the Python sidecar is missing, speech detection is degraded (much lower recall).
   */
  detector: "silero-vad+spectral" | "spectral-only";
  segments: {
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    start: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    end: number;
    label: "silence" | "noise" | "music" | "speech" | "speech+noise" | "speech+music";
  }[];
  /**
   * Share of the source where speech is present but the background under it could not be measured (continuous speech, no pause or background heard alone nearby). A music bed there is NOT detected (measured limit): music cannot be ruled out.
   */
  speechBackgroundUnknown: number;
  /**
   * Share of the source duration holding each class (speech+music counts for both).
   */
  shares: {
    speech: number;
    music: number;
    noise: number;
    silence: number;
  };
}

/**
 * Dialogue processing chains (audio-cleanup), music bed (music) and master bus. Compiled into FFmpeg filtergraphs; parameters stay editable.
 */
export interface AudioDoc {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  dialogue: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    sourceId: string;
    preset?: "off" | "gentle" | "standard" | "aggressive" | "custom";
    chain: Processor[];
    measurements?: {
      before?: Metrics;
      after?: Metrics;
    };
    /**
     * Measured neural-denoise decision for this source (chantier 2). Recorded even when nothing is applied.
     */
    denoise?: {
      /**
       * Reference-free SNR estimate in the voice band.
       */
      estimatedSnrDb: number;
      /**
       * skip-music: the analysis found music in this source; a denoiser would remove it as noise (chantier 4).
       */
      decision: "skip-clean" | "skip-strong-noise" | "applied" | "rejected-all" | "unavailable" | "skip-music";
      mix?: number;
      summary: string;
      candidates?: {
        mix: number;
        accepted: boolean;
        reasons?: string[];
        voiceLevelDeltaDb?: number;
        voiceSpectralChangeDb?: number;
        snrBeforeDb?: number;
        snrAfterDb?: number;
      }[];
    };
  }[];
  music?: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    assetId: string;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    assetIn?: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    timelineStart?: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    timelineEnd?: number;
    gainDb?: number;
    fadeInSec?: number;
    fadeOutSec?: number;
    ducking?: {
      enabled?: boolean;
      amountDb?: number;
      attackMs?: number;
      releaseMs?: number;
    };
    /**
     * Beat/downbeat/drop analysis file for this asset.
     */
    beatsRef?: string;
  }[];
  master: {
    /**
     * Usually taken from the target preset (-14 social, -23 broadcast).
     */
    loudnessLufs: number;
    truePeakDb: number;
    limiter?: boolean;
  };
}
export interface Processor {
  type:
    | "highpass"
    | "lowpass"
    | "dehum"
    | "denoise-fft"
    | "denoise-rnn"
    | "gate"
    | "deess"
    | "eq"
    | "compressor"
    | "dereverb"
    | "gain"
    | "limiter";
  enabled?: boolean;
  /**
   * Processor-specific; validated by the engine's processor registry.
   */
  params?: {};
  reason?: string;
}
export interface Metrics {
  integratedLufs?: number;
  truePeakDb?: number;
  noiseFloorDb?: number;
  speechToNoiseDb?: number;
}

/**
 * Machine-readable brand identity. Consumed by every skill that makes a visual, motion, caption or audio decision.
 */
export interface Brand {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  name: string;
  identity: {
    /**
     * @minItems 1
     * @maxItems 4
     */
    primaryColors:
      | [ColorToken]
      | [ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken, ColorToken];
    /**
     * @maxItems 6
     */
    secondaryColors?:
      | []
      | [ColorToken]
      | [ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken, ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken, ColorToken, ColorToken, ColorToken];
    /**
     * @maxItems 4
     */
    accentColors?:
      | []
      | [ColorToken]
      | [ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken]
      | [ColorToken, ColorToken, ColorToken, ColorToken];
    neutrals?: {
      background?: string;
      foreground?: string;
      muted?: string;
    };
    /**
     * @minItems 1
     */
    fonts: [Font, ...Font[]];
    logo: Logo;
  };
  visual: {
    contrast: "low" | "medium" | "high";
    /**
     * Corner radius in px at 1080p reference height.
     */
    radius: number;
    shadows: "none" | "soft" | "hard" | "glow";
    composition: "centered" | "asymmetric" | "grid" | "editorial";
    shapes?: "none" | "line" | "block" | "pill" | "circle";
    density?: "airy" | "balanced" | "dense";
    texture?: "clean" | "grain" | "paper" | "noise";
  };
  /**
   * Brand look applied AFTER technical color correction.
   */
  grade?: {
    look?: "natural" | "warm" | "cool" | "filmic" | "high-contrast" | "muted" | "vibrant" | "mono";
    intensity?: number;
    /**
     * Normalized adjustment. 0 = neutral.
     */
    saturation?: number;
    /**
     * Normalized adjustment. 0 = neutral.
     */
    warmth?: number;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    lut?: string;
    protectSkinTones?: boolean;
  };
  motion: {
    speed: "slow" | "medium" | "fast";
    easing:
      | ("linear" | "standard" | "emphasized" | "decelerate" | "spring-soft" | "spring-snappy" | "bounce")
      | [number, number, number, number];
    amplitude: "subtle" | "moderate" | "bold";
    transitionStyle: "cut" | "fade" | "slide" | "wipe" | "mask" | "zoom" | "blur";
    /**
     * 0 = still/minimal, 1 = kinetic. Drives stagger, overshoot and secondary motion.
     */
    energy?: number;
    /**
     * Free keywords, e.g. 'precise', 'playful', 'luxurious'.
     *
     * @maxItems 6
     */
    personality?:
      | []
      | [string]
      | [string, string]
      | [string, string, string]
      | [string, string, string, string]
      | [string, string, string, string, string]
      | [string, string, string, string, string, string];
  };
  caption: {
    /**
     * Font role ('display'|'body'|'caption') or explicit family name.
     */
    font: string;
    weight?: number;
    sizeScale?: number;
    position: "bottom" | "center" | "lower-third" | "auto";
    textColor?: string;
    highlightColor: string;
    background?: "none" | "box" | "shadow" | "stroke";
    case?: "as-spoken" | "sentence" | "upper";
    animation: "none" | "fade" | "pop" | "karaoke" | "word-by-word" | "slide";
    emphasisStyle?: "color" | "scale" | "box" | "underline" | "weight";
    maxWordsPerLine?: number;
    maxLines?: number;
  };
  audio: {
    energy: "calm" | "moderate" | "high";
    voiceStyle: string;
    musicMoods?: string[];
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    sonicLogo?: string;
  };
  /**
   * Verbal identity used when Claude writes on-screen copy (titles, CTA).
   */
  tone?: {
    keywords?: string[];
    do?: string[];
    dont?: string[];
  };
  /**
   * Map of JSON pointer (e.g. '/motion/speed') to where the value came from.
   */
  provenance?: {
    /**
     * Where a value came from — makes every decision explainable.
     */
    [k: string]: {
      source: "user" | "extracted" | "inferred" | "default";
      confidence?: number;
      evidence?: string;
    };
  };
}
export interface ColorToken {
  name?: string;
  hex: string;
  /**
   * e.g. 'backgrounds', 'CTA only', 'never on text'
   */
  usage?: string;
}
export interface Font {
  role: "display" | "body" | "caption" | "mono";
  family: string;
  weights?: number[];
  source?: {
    kind: "file" | "google" | "system";
    /**
     * Single file (a variable font covers every weight).
     */
    path?: string;
    /**
     * One file per weight (static fonts). Project-relative, usually brand/fonts/.
     */
    files?: {
      weight: number;
      /**
       * Path relative to the project root. Absolute paths and parent traversal are rejected.
       */
      path: string;
    }[];
  };
  /**
   * Font used when the brand font is unavailable. Fetch its files with `bve brand fonts fetch` so rendering never depends on installed fonts.
   */
  fallback?: string;
  /**
   * Files of the fallback font, used when the brand font files are missing or unlicensed.
   */
  fallbackSource?: {
    kind: "file" | "google" | "system";
    /**
     * Single file (a variable font covers every weight).
     */
    path?: string;
    /**
     * One file per weight (static fonts). Project-relative, usually brand/fonts/.
     */
    files?: {
      weight: number;
      /**
       * Path relative to the project root. Absolute paths and parent traversal are rejected.
       */
      path: string;
    }[];
  };
  /**
   * e.g. OFL-1.1, commercial (licensed to the brand).
   */
  license?: string;
}
export interface Logo {
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  primary: string;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  monochrome?: string;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  icon?: string;
  /**
   * Minimum clear space as a fraction of logo height.
   */
  clearSpace?: number;
  /**
   * At 1080p reference height.
   */
  minHeightPx?: number;
  allowedBackgrounds?: string[];
  watermark?: {
    anchor?:
      | "top-left"
      | "top"
      | "top-right"
      | "left"
      | "center"
      | "right"
      | "bottom-left"
      | "bottom"
      | "bottom-right"
      | "lower-third"
      | "safe-bottom"
      | "auto";
    opacity?: number;
  };
}

/**
 * Segmented, emphasis-tagged captions in OUTPUT (timeline) time. Style resolves from Brand DNA unless overridden. Layout is resolved per target at render time against safe zones.
 */
export interface Captions {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  language: string;
  /**
   * 'ass' = libass fallback (fast, fewer animations).
   */
  renderer?: "remotion" | "ass";
  /**
   * Partial Brand DNA 'caption' object.
   */
  styleOverrides?: {};
  cues: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    id: string;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    start: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    end: number;
    /**
     * @minItems 1
     */
    words: [
      {
        text: string;
        /**
         * Time in seconds. Snapped to the nearest frame at render time.
         */
        start: number;
        /**
         * Time in seconds. Snapped to the nearest frame at render time.
         */
        end: number;
        emphasis?: "none" | "strong" | "key";
        lineBreakAfter?: boolean;
      },
      ...{
        text: string;
        /**
         * Time in seconds. Snapped to the nearest frame at render time.
         */
        start: number;
        /**
         * Time in seconds. Snapped to the nearest frame at render time.
         */
        end: number;
        emphasis?: "none" | "strong" | "key";
        lineBreakAfter?: boolean;
      }[]
    ];
    anchor?:
      | "top-left"
      | "top"
      | "top-right"
      | "left"
      | "center"
      | "right"
      | "bottom-left"
      | "bottom"
      | "bottom-right"
      | "lower-third"
      | "safe-bottom"
      | "auto";
    /**
     * e.g. hidden while a full-screen Title is on.
     */
    hidden?: boolean;
  }[];
}

/**
 * @minItems 3
 * @maxItems 3
 */
export type Rgb = [number, number, number];

/**
 * Per-shot color. 'correction' makes the image technically right (exposure, WB, matching). 'grade' applies the creative/brand look on top. Both are parameters, never baked into sources.
 */
export interface ColorDoc {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  globalGrade?: ShotGrade;
  shots: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    sourceId: string;
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    shotId: string;
    correction?: Correction;
    grade?: ShotGrade1;
    /**
     * shotId used as reference for camera matching.
     */
    matchTo?: string;
    /**
     * User-approved; auto passes must not change it.
     */
    locked?: boolean;
    measurements?: {
      before?: Stats;
      after?: Stats;
    };
    reason?: string;
  }[];
}
export interface ShotGrade {
  look?: "none" | "natural" | "warm" | "cool" | "filmic" | "high-contrast" | "muted" | "vibrant" | "mono";
  intensity?: number;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  lut?: string;
  lift?: Rgb;
  gamma?: Rgb;
  gain?: Rgb;
}
export interface Correction {
  /**
   * Stops.
   */
  exposure?: number;
  /**
   * Normalized adjustment. 0 = neutral.
   */
  contrast?: number;
  /**
   * Normalized adjustment. 0 = neutral.
   */
  highlights?: number;
  /**
   * Normalized adjustment. 0 = neutral.
   */
  shadows?: number;
  /**
   * Normalized adjustment. 0 = neutral.
   */
  whites?: number;
  /**
   * Normalized adjustment. 0 = neutral.
   */
  blacks?: number;
  /**
   * Normalized adjustment. 0 = neutral.
   */
  saturation?: number;
  /**
   * -1 cooler … +1 warmer.
   */
  temperature?: number;
  /**
   * -1 green … +1 magenta.
   */
  tint?: number;
  whiteBalance?: {
    mode?: "as-shot" | "auto-gray-world" | "auto-skin" | "manual";
    /**
     * @minItems 3
     * @maxItems 3
     */
    gains?: [number, number, number];
  };
  protectSkinTones?: boolean;
}
/**
 * Per-shot override of globalGrade.
 */
export interface ShotGrade1 {
  look?: "none" | "natural" | "warm" | "cool" | "filmic" | "high-contrast" | "muted" | "vibrant" | "mono";
  intensity?: number;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  lut?: string;
  lift?: Rgb;
  gamma?: Rgb;
  gain?: Rgb;
}
export interface Stats {
  lumaMean?: number;
  lumaP05?: number;
  lumaP95?: number;
  saturationMean?: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  rgbMean?: [number, number, number];
}

/**
 * Point to material by exact range, by transcript segment, or by analysed shot.
 */
export type SourceRef =
  | {
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      sourceId: string;
      /**
       * Time in seconds. Snapped to the nearest frame at render time.
       */
      start: number;
      /**
       * Time in seconds. Snapped to the nearest frame at render time.
       */
      end: number;
    }
  | {
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      segmentId: string;
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      sourceId?: string;
    }
  | {
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      shotId: string;
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      sourceId: string;
    };

/**
 * Semantic intent authored by the creative-director skill (brief + analysis + Brand DNA). The engine compiles it into timeline/color/audio/captions/motion documents. Editing the plan never touches sources.
 */
export interface CreativePlan {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  objective: string;
  targetDurationSec: number;
  durationToleranceSec?: number;
  /**
   * Project target ids this plan is written for.
   */
  targets?: string[];
  narrative: {
    structure:
      | "hook-problem-solution-cta"
      | "aida"
      | "pas"
      | "story-arc"
      | "listicle"
      | "demo"
      | "testimonial"
      | "teaser"
      | "custom";
    rationale?: string;
  };
  hook: {
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    start: number;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    end: number;
    technique: "bold-claim" | "question" | "result-first" | "pattern-interrupt" | "stat" | "visual-reveal" | "quote";
    sourceRefs?: SourceRef[];
    onScreenText?: string;
  };
  /**
   * @minItems 1
   */
  sections: [
    {
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      id: string;
      role:
        "hook" | "context" | "problem" | "solution" | "proof" | "demo" | "benefit" | "testimonial" | "cta" | "outro";
      intent?: string;
      sourceRefs: SourceRef[];
      targetDurationSec?: number;
      broll?: SourceRef[];
      onScreenText?: string;
      /**
       * Motion component names requested for this section (resolved by motion-brand).
       */
      motion?: string[];
    },
    ...{
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      id: string;
      role:
        "hook" | "context" | "problem" | "solution" | "proof" | "demo" | "benefit" | "testimonial" | "cta" | "outro";
      intent?: string;
      sourceRefs: SourceRef[];
      targetDurationSec?: number;
      broll?: SourceRef[];
      onScreenText?: string;
      /**
       * Motion component names requested for this section (resolved by motion-brand).
       */
      motion?: string[];
    }[]
  ];
  pacing: {
    style: "calm" | "medium" | "fast" | "aggressive";
    avgShotSec?: number;
    jumpCuts?: boolean;
    punchIns?: boolean;
    removeSilences?: {
      enabled?: boolean;
      minSilenceSec?: number;
      keepPaddingSec?: number;
    };
    removeFillers?: boolean;
  };
  transitions?: {
    default?: "cut" | "brand";
    betweenSections?: "cut" | "brand" | "fade" | "dissolve";
  };
  music?: {
    enabled?: boolean;
    mood?: string;
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    assetId?: string;
    /**
     * @minItems 2
     * @maxItems 2
     */
    bpmRange?: [number, number];
    syncCutsToBeats?: boolean;
    duckUnderVoiceDb?: number;
  };
  captions?: {
    enabled?: boolean;
    emphasis?: "auto" | "manual" | "off";
    language?: string;
  };
  motion?: {
    density?: "none" | "low" | "medium" | "high";
    intro?: "none" | "BrandIntro" | "LogoReveal";
    outro?: "none" | "BrandOutro" | "LogoReveal";
    lowerThirds?: {
      name: string;
      title?: string;
      at?: number;
    }[];
  };
  cta?: {
    text: string;
    subtext?: string;
    at?: number | "end";
    durationSec?: number;
  };
  logo?: {
    watermark?: boolean;
  };
  color?: {
    intent?: "correct-only" | "brand-look" | "custom";
    notes?: string;
  };
  audio?: {
    cleanup?: "off" | "gentle" | "standard" | "aggressive";
  };
  /**
   * Plain-language justification of key choices, shown to the user.
   */
  rationale?: string[];
}

export type Instance = {
  [k: string]: unknown;
} & {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  component: ComponentName;
  /**
   * Time in seconds. Snapped to the nearest frame at render time.
   */
  start: number;
  durationSec: number;
  layer?: number;
  anchor?:
    | "top-left"
    | "top"
    | "top-right"
    | "left"
    | "center"
    | "right"
    | "bottom-left"
    | "bottom"
    | "bottom-right"
    | "lower-third"
    | "safe-bottom"
    | "auto";
  /**
   * Restrict to some targets; omitted = all.
   */
  targets?: string[];
  /**
   * Optional component variant; default is chosen from Brand DNA.
   */
  variant?: string;
  /**
   * Local deviation from Brand DNA motion tokens. QC reports every override.
   */
  tokenOverrides?: {
    speed?: "slow" | "medium" | "fast";
    amplitude?: "subtle" | "moderate" | "bold";
    colorRole?: "primary" | "secondary" | "accent" | "neutral";
  };
  props: {};
  reason?: string;
};
export type ComponentName =
  | "BrandIntro"
  | "BrandOutro"
  | "LogoReveal"
  | "Title"
  | "Subtitle"
  | "LowerThird"
  | "CTA"
  | "Quote"
  | "Statistic"
  | "ProductReveal"
  | "FeatureCard"
  | "Callout"
  | "Transition"
  | "Watermark";

/**
 * Instances of brand motion components on the output timeline. Visual style (colors, fonts, easing, speed, amplitude, shapes) is NOT stored here: it is derived from Brand DNA at render time, so changing the brand restyles every instance.
 */
export interface MotionDoc {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  instances: Instance[];
}

/**
 * Root of a post-production project. Registers sources/assets, points to the current documents and tracks versions and exports. Source media are referenced, never modified.
 */
export interface ProjectManifest {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  name: string;
  createdAt: string;
  updatedAt?: string;
  engineVersion: string;
  brief?: {
    /**
     * User brief, verbatim.
     */
    text?: string;
    objective?: "awareness" | "conversion" | "education" | "engagement" | "recruitment" | "other";
    audience?: string;
    tone?: string;
    language?: string;
    targetDurationSec?: number;
  };
  sources: Source[];
  assets?: Asset[];
  /**
   * Working-copy paths of the mutable documents. Snapshotted on every version.
   */
  documents: {
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    brand?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    analysis?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    transcript?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    plan?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    timeline?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    color?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    audio?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    captions?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    motion?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    styleTokens?: string;
  };
  /**
   * Output formats to produce. Each references a preset in presets/.
   */
  targets: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    id: string;
    /**
     * e.g. 'instagram/reels', 'youtube/landscape'
     */
    preset: string;
    /**
     * Shallow overrides of preset fields (e.g. maxDurationSec).
     */
    overrides?: {};
  }[];
  versioning: {
    head: string;
    autoCommit?: boolean;
  };
  exports?: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    id: string;
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    targetId: string;
    version: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    path: string;
    sha256: string;
    createdAt: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    qcReport: string;
  }[];
}
export interface Source {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  /**
   * Usually under source/. Read-only.
   */
  path: string;
  /**
   * Informational: where the user file came from.
   */
  originalPath?: string;
  sha256: string;
  bytes: number;
  role?: "a-roll" | "b-roll" | "music" | "voiceover" | "other";
  probe: Probe;
  /**
   * Constant-frame-rate, edit-friendly copy used by the engine when the source is VFR or long-GOP.
   */
  mezzanine?: string;
  /**
   * Low-res copy used for analysis and previews.
   */
  proxy?: string;
}
export interface Probe {
  durationSec: number;
  hasVideo: boolean;
  hasAudio: boolean;
  width?: number;
  height?: number;
  rotation?: 0 | 90 | 180 | 270 | -90 | -180 | -270;
  fps?: number;
  fpsMode?: "cfr" | "vfr";
  videoCodec?: string;
  pixFmt?: string;
  colorSpace?: string;
  /**
   * Signalled YUV range (absent = unsignalled).
   */
  colorRange?: "tv" | "pc";
  colorTransfer?: string;
  bitDepth?: number;
  audioCodec?: string;
  sampleRate?: number;
  channels?: number;
}
export interface Asset {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  kind: "logo" | "image" | "font" | "music" | "sfx" | "lut" | "video" | "brandbook" | "reference";
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  path: string;
  sha256?: string;
  /**
   * License / usage rights. QC warns on missing license for music and fonts.
   */
  license?: string;
}

/**
 * Result of quality-control on one rendered target. Any failed check with severity 'blocker' makes status 'fail' and prevents export.
 */
export interface QcReport {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  targetId: string;
  version: string;
  createdAt: string;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  renderPath: string;
  status: "pass" | "warn" | "fail";
  categories: {
    technical?: Category;
    audio?: Category;
    captions?: Category;
    color?: Category;
    brand?: Category;
    motion?: Category;
    export?: Category;
  };
}
export interface Category {
  status: "pass" | "warn" | "fail" | "skip";
  checks: {
    /**
     * e.g. 'technical.resolution', 'audio.loudness', 'captions.safe-zone'
     */
    id: string;
    status: "pass" | "warn" | "fail" | "skip";
    severity: "blocker" | "major" | "minor" | "info";
    message: string;
    expected?: unknown;
    measured?: unknown;
    at?: {
      /**
       * Time in seconds. Snapped to the nearest frame at render time.
       */
      start: number;
      /**
       * Time in seconds. Snapped to the nearest frame at render time.
       */
      end: number;
    };
    /**
     * Suggested remediation (skill + command).
     */
    fix?: string;
  }[];
}

/**
 * Deterministic compilation of Brand DNA for one fps. The ONLY style input accepted by motion components, caption renderers and the color look. Pixel values are expressed for a 1080 px short side and scaled by the renderer.
 */
export interface StyleTokens {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  brandName: string;
  /**
   * sha256 of the brand.json these tokens were compiled from.
   */
  brandHash: string;
  fps: number;
  color: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    foreground: string;
    muted: string;
    onPrimary: string;
    onAccent: string;
    /**
     * Every brand color; QC checks rendered graphics against it.
     */
    palette?: string[];
  };
  type: {
    display: TokenFont;
    body: TokenFont;
    caption: TokenFont;
  };
  shape: {
    style: "none" | "line" | "block" | "pill" | "circle";
    radiusPx: number;
    shadow: "none" | "soft" | "hard" | "glow";
    strokePx: number;
  };
  motion: {
    enterFrames: number;
    exitFrames: number;
    minHoldFrames: number;
    staggerFrames: number;
    easing:
      | {
          kind: "bezier";
          /**
           * @minItems 4
           * @maxItems 4
           */
          bezier: [number, number, number, number];
        }
      | {
          kind: "spring";
          damping: number;
          stiffness: number;
          mass: number;
        };
    distancePx: number;
    scaleFrom: number;
    overshoot: number;
    transition: "cut" | "fade" | "slide" | "wipe" | "mask" | "zoom" | "blur";
    transitionFrames: number;
    energy: number;
  };
  caption: {
    family: string;
    fallback?: string;
    weight: number;
    sizePx: number;
    case: "as-spoken" | "sentence" | "upper";
    position: "bottom" | "center" | "lower-third" | "auto";
    animation: "none" | "fade" | "pop" | "karaoke" | "word-by-word" | "slide";
    emphasisStyle: "color" | "scale" | "box" | "underline" | "weight";
    background: "none" | "box" | "shadow" | "stroke";
    maxWordsPerLine: number;
    maxLines: number;
    textColor: string;
    highlightColor: string;
    strokePx: number;
  };
  layout: {
    density: "airy" | "balanced" | "dense";
    composition: "centered" | "asymmetric" | "grid" | "editorial";
    marginPx: number;
  };
  grade: {
    look: "natural" | "warm" | "cool" | "filmic" | "high-contrast" | "muted" | "vibrant" | "mono";
    intensity: number;
    /**
     * Normalized adjustment. 0 = neutral.
     */
    saturation: number;
    /**
     * Normalized adjustment. 0 = neutral.
     */
    warmth: number;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    lut?: string;
    protectSkinTones?: boolean;
  };
  logo?: {
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    primary: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    monochrome?: string;
    clearSpace?: number;
    minHeightPx?: number;
    watermark?: {
      anchor?: string;
      opacity?: number;
    };
  };
}
export interface TokenFont {
  family: string;
  weight: number;
  fallback?: string;
  files?: {
    weight: number;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    path: string;
  }[];
  fallbackFiles?: {
    weight: number;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    path: string;
  }[];
}

/**
 * Non-destructive, format-agnostic edit. Clips reference source ranges; per-target reframing is stored separately so one edit yields every aspect ratio.
 */
export interface Timeline {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  fps: 23.976 | 24 | 25 | 29.97 | 30 | 50 | 59.94 | 60;
  /**
   * Computed by the engine; informational.
   */
  durationSec?: number;
  tracks: {
    video: VideoTrack[];
    audio: AudioTrack[];
  };
  transitions?: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    id: string;
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    fromClip: string;
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    toClip: string;
    /**
     * 'brand' = use Brand DNA transitionStyle.
     */
    type: "cut" | "fade" | "dissolve" | "dip-to-color" | "slide" | "wipe" | "zoom" | "brand";
    durationSec: number;
  }[];
  markers?: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    id: string;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    time: number;
    kind: "hook" | "section" | "cta" | "beat" | "drop" | "note";
    label?: string;
  }[];
  /**
   * Keyed by target id. How each clip is cropped for that target's aspect ratio.
   */
  reframe?: {
    [k: string]: ReframePlan;
  };
}
export interface VideoTrack {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  kind: "primary" | "broll";
  clips: Clip[];
}
export interface Clip {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  sourceId: string;
  /**
   * Time in seconds. Snapped to the nearest frame at render time.
   */
  sourceIn: number;
  /**
   * Time in seconds. Snapped to the nearest frame at render time.
   */
  sourceOut: number;
  /**
   * Time in seconds. Snapped to the nearest frame at render time.
   */
  timelineStart: number;
  speed?: number;
  enabled?: boolean;
  /**
   * Creative-plan section this clip belongs to.
   */
  sectionId?: string;
  /**
   * Why this clip exists / was trimmed. Used to explain edits.
   */
  reason?: string;
  /**
   * Punch-in keyframes (clip-relative time). Used for jump-cut variety and emphasis.
   */
  zoom?: {
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    t: number;
    scale: number;
    ease?: "hold" | "linear" | "brand";
  }[];
}
export interface AudioTrack {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  id: string;
  kind: "dialogue" | "music" | "sfx";
  /**
   * Dialogue track that mirrors a video track's cuts (linked A/V).
   */
  followVideoTrack?: string;
  clips: Clip[];
}
export interface ReframePlan {
  mode: "fit-blur" | "center" | "face" | "subject" | "manual";
  smoothingSec?: number;
  keyframes?: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    clipId: string;
    /**
     * Time in seconds. Snapped to the nearest frame at render time.
     */
    t: number;
    /**
     * Crop window center, normalized to source width.
     */
    cx: number;
    cy: number;
    scale?: number;
  }[];
}

/**
 * Word-level transcript in SOURCE time. Captions are derived from it by remapping through the timeline.
 */
export interface Transcript {
  /**
   * Major.minor. Major bumps are breaking and require a migration.
   */
  schemaVersion: string;
  language: string;
  /**
   * e.g. 'faster-whisper/large-v3'
   */
  model: string;
  sources: {
    /**
     * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
     */
    sourceId: string;
    segments: {
      /**
       * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
       */
      id: string;
      /**
       * Time in seconds. Snapped to the nearest frame at render time.
       */
      start: number;
      /**
       * Time in seconds. Snapped to the nearest frame at render time.
       */
      end: number;
      text: string;
      speaker?: string;
      words: {
        w: string;
        /**
         * Time in seconds. Snapped to the nearest frame at render time.
         */
        start: number;
        /**
         * Time in seconds. Snapped to the nearest frame at render time.
         */
        end: number;
        /**
         * Confidence.
         */
        p?: number;
        /**
         * Hesitation ('euh', 'um', 'du coup'...).
         */
        filler?: boolean;
      }[];
    }[];
  }[];
}

/**
 * Delivery format for one platform: geometry, encoding, loudness and UI safe zones.
 */
export interface Preset {
  id: string;
  label: string;
  width: number;
  height: number;
  fps: number;
  aspectRatio: "16:9" | "9:16" | "1:1" | "4:5";
  maxDurationSec?: number;
  maxFileSizeMb?: number;
  video: {
    codec: "h264" | "prores";
    profile?: string;
    crf?: number;
    maxBitrateKbps?: number;
    pixFmt: "yuv420p" | "yuv422p10le";
  };
  audio: {
    codec: "aac" | "pcm_s24le";
    bitrateKbps?: number;
    sampleRate: 44100 | 48000;
  };
  loudness: {
    integratedLufs: number;
    truePeakDb: number;
    toleranceLu: number;
  };
  /**
   * Insets (fraction of width/height) where platform UI may cover the picture. Text and logos must stay inside.
   */
  safeZone: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
}

/**
 * Written by the renderer next to every render; the contract between rendering, QC and export.
 */
export interface RenderRecord {
  /**
   * Stable, human-readable identifier (e.g. 'src_interview', 'clip_012').
   */
  targetId: string;
  version: string;
  draft: boolean;
  renderer: "remotion" | "ass" | "none";
  rendererNote?: string;
  /**
   * Path relative to the project root. Absolute paths and parent traversal are rejected.
   */
  path: string;
  sha256: string;
  durationSec: number;
  stages: {
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    base: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    graphics?: string;
    /**
     * Path relative to the project root. Absolute paths and parent traversal are rejected.
     */
    mix: string;
  };
  cacheHits: ("base" | "graphics" | "mix")[];
  /**
   * Font actually used per role, as verified by the renderer.
   */
  fonts?: {
    role: "display" | "body" | "caption";
    requested: string;
    used?: string;
    status: "found" | "fallback" | "missing" | "unverified";
    detail?: string;
  }[];
  createdAt: string;
}

/**
 * User decisions to accept a blocking QC check. Written only by `bve qc waive`.
 */
export type QcWaivers = {
  checkId: string;
  reason: string;
  at: string;
}[];

