/**
 * Generates TypeScript types from schemas/*.schema.json (the single source of truth).
 * Output: engine/core/src/types.generated.ts — never edit that file by hand.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "..");
const schemaDir = join(root, "schemas");
const outFile = join(root, "engine/core/src/types.generated.ts");

const TYPE_NAMES: Record<string, string> = {
  "analysis.schema.json": "Analysis",
  "audio.schema.json": "AudioDoc",
  "brand.schema.json": "Brand",
  "captions.schema.json": "Captions",
  "color.schema.json": "ColorDoc",
  "creative-plan.schema.json": "CreativePlan",
  "motion.schema.json": "MotionDoc",
  "project.schema.json": "ProjectManifest",
  "qc-report.schema.json": "QcReport",
  "style-tokens.schema.json": "StyleTokens",
  "timeline.schema.json": "Timeline",
  "transcript.schema.json": "Transcript",
  "preset.schema.json": "Preset",
  "render-record.schema.json": "RenderRecord",
  "qc-waivers.schema.json": "QcWaivers",
};

const schemas = new Map<string, JSONSchema>();
for (const f of readdirSync(schemaDir)) schemas.set(f, JSON.parse(readFileSync(join(schemaDir, f), "utf8")));

/** Inline cross-file refs ("common.schema.json#/$defs/x") so the generator needs no custom resolver. */
function inlineRefs(node: unknown, rootFile: string, currentFile: string): unknown {
  if (Array.isArray(node)) return node.map((n) => inlineRefs(n, rootFile, currentFile));
  if (node && typeof node === "object") {
    const obj = node as Record<string, unknown>;
    const ref = obj.$ref;
    if (typeof ref === "string") {
      const [filePart, pointer = ""] = ref.split("#");
      const file = filePart || currentFile;
      // Local refs of the root schema stay refs: the generator names them.
      if (file !== rootFile) {
        const target = schemas.get(file);
        if (!target) throw new Error(`Unresolvable $ref ${ref} (in ${currentFile})`);
        const resolved = pointer.split("/").filter(Boolean).reduce<any>((acc, key) => acc?.[key], target);
        if (resolved === undefined) throw new Error(`Unresolvable pointer ${ref} (in ${currentFile})`);
        const { $ref: _drop, ...rest } = obj;
        return inlineRefs({ ...resolved, ...rest }, rootFile, file);
      }
      return { ...obj, $ref: `#${pointer}` };
    }
    return Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, inlineRefs(v, rootFile, currentFile)]));
  }
  return node;
}

let out = "/* eslint-disable */\n// AUTO-GENERATED by scripts/gen-types.ts from schemas/*.schema.json — DO NOT EDIT.\n\n";
for (const [file, name] of Object.entries(TYPE_NAMES)) {
  const schema = schemas.get(file);
  if (!schema) continue;
  const prepared = inlineRefs({ ...schema, $id: undefined, title: name }, file, file) as JSONSchema;
  const ts = await compile(prepared, name, { bannerComment: "", additionalProperties: false, strictIndexSignatures: false, unreachableDefinitions: false, format: true });
  out += ts + "\n";
}
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out);
console.log(`wrote ${outFile}`);
